version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    volumes:
      - ./database.sql:/usr/src/app/thedatabase.sqlite
    environment:
      - NODE_ENV=production
